spring:
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: sajotuna

  cloud:
    config:
      enabled: false

  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        highlight_sql: true
        auto_quote_keyword: true

rabbitmq:
  point:
    queue: sajotuna.point.queue
    exchange: sajotuna.point.exchange
    routing-key: sajotuna.point.earn
    dlx-queue: sajotuna.point.dlq
    dlx-exchange: sajotuna.point.dlx
    dlx-routing-key: sajotuna.point.earn.error
    parking-lot-queue: sajotuna.point.parking.queue
    parking-lot-exchange: sajotuna.point.parking.exchange
    parking-lot-routing-key: sajotuna.point.earn.dead
logging:
  level:
    com.netflix.discovery: off
    com.netflix.eureka: off
    org.springframework.cloud.netflix.eureka: off