### 주문 조회
GET localhost:10366/api/orders/1

### 회원의 주문내역 조회
GET localhost:10366/api/orders/user
X-User-Id: 1

### 대기 중인 주문들 조회
GET localhost:10366/api/orders/pending

### 배송 중으로 전환
PUT localhost:10366/api/orders/pending/1

### 회원 주문
POST localhost:10366/api/orders/user
Content-Type: application/json
X-User-Id: 1

{
  "shippingDate": "20250612123456",
  "streetAddress": "test",
  "deliveryPrice": 1000,
  "usedPoint": 1000,
  "usedUserCoupon": 1,
  "method": "CARD",
  "items": [
    {
      "orderPackagingId": 1,
      "isbn": "test",
      "qty": 2,
      "amount": 10000,
      "packagingRequest": true
    },
    {
      "isbn": "test2",
      "qty": 1,
      "amount": 5990,
      "packagingRequest": false
    }
  ]
}

### 비회원 주문
POST localhost:10366/api/orders/guest
Content-Type: application/json

{
  "name": "test",
  "phoneNumber": "010-1234-5678",
  "email": "test@gmail.com",
  "shippingDate": "20250612123456",
  "streetAddress": "test",
  "deliveryPrice": 1000,
  "method": "CARD",
  "items": [
    {
      "orderPackagingId": 1,
      "isbn": "test",
      "qty": 2,
      "amount": 10000,
      "packagingRequest": true
    },
    {
      "isbn": "test2",
      "qty": 1,
      "amount": 5990,
      "packagingRequest": false
    }
  ]
}

### 주문 반품
PUT localhost:10366/api/orders/returned/2
Content-Type: application/json

{
  "userId": 1
}

### 주문 취소
PUT localhost:10366/api/orders/cancelled/1

### 주문 상품 조회
GET localhost:10366/api/orders/product/1

### 주문 번호에 포함된 상품들 조회
GET localhost:10366/api/orders/product/list/1

### package 목록 조회
GET localhost:10366/api/orders/package





### 주문 목록 조회
GET localhost:10366/api/admin/orders?status=fewfdsfds

### 주문 배송 중으로 전환
PUT localhost:10366/api/admin/orders/pending/1

### package 추가
POST localhost:10366/api/admin/orders/package
Content-Type: application/json

{
  "packaging": "test",
  "price": 1000
}

### package 수정
PUT localhost:10366/api/admin/orders/package/1
Content-Type: application/json

{
  "packaging": "change",
  "price": 5400
}