### 주문 조회
GET localhost:10366/api/orders/1

### 회원의 주문내역 조회
GET localhost:10366/api/orders/user
X-User-Id: 19

### 회원 주문
POST localhost:10366/api/orders
Content-Type: application/json
X-User-Id: 1

{
  "ordererName": "홍길동",
  "ordererPhoneNumber": "010-1234-5678",
  "ordererEmail": "hong@example.com",
  "recipientName": "김수령",
  "recipientPhoneNumber": "010-9876-5432",
  "recipientEmail": "kim@example.com",
  "recipientAddress": "서울시 강남구 테헤란로 123",
  "expectedDeliveryDate": "20250710081219",
  "orderCouponId": 6,
  "usedPoint": 1000,
  "items": [
    {
      "orderPackagingId": 1,
      "isbn": "test",
      "qty": 2,
      "amount": 70000,
      "packagingRequest": true
    },
    {
      "isbn": "test2",
      "qty": 1,
      "amount": 5990,
      "packagingRequest": false
    }
  ]
}

### 주문 상품 조회
GET localhost:10366/api/orders/product/1

### 주문 번호에 포함된 상품들 조회
GET localhost:10366/api/orders/product/list/2

### 주문 목록 조회
GET localhost:10366/api/admin/orders?page=0&size=5

### 배송 상태에 따라 주문 목록 조회
GET localhost:10366/api/admin/orders/pending?page=0&size=5

### 게스트 주문 조회
GET localhost:10366/api/orders/guest/bYY4mqih9Jvs5CH

### 게스트 주문 생성
POST localhost:10366/api/orders
Content-Type: application/json

{
  "ordererName": "홍길동",
  "ordererPhoneNumber": "010-1234-5678",
  "ordererEmail": "hong@example.com",
  "recipientName": "김수령",
  "recipientPhoneNumber": "010-9876-5432",
  "recipientEmail": "kim@example.com",
  "recipientAddress": "서울시 강남구 테헤란로 123",
  "expectedDeliveryDate": "20250710081219",
  "orderCouponId": null,
  "usedPoint": 0,
  "items": [
    {
      "orderPackagingId": 1,
      "isbn": "test",
      "qty": 1,
      "amount": 15000,
      "packagingRequest": false
    }
  ]
}

### 주문 폼 데이터 조회
GET localhost:10366/api/orders/form
X-User-Id: 1